/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jogamp_common_os_Platform */

#ifndef _Included_com_jogamp_common_os_Platform
#define _Included_com_jogamp_common_os_Platform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jogamp_common_os_Platform
 * Method:    currentTimeMillis
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_com_jogamp_common_os_Platform_currentTimeMillis
  (JNIEnv *, jclass);

/*
 * Class:     com_jogamp_common_os_Platform
 * Method:    currentTimeMicros
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_com_jogamp_common_os_Platform_currentTimeMicros
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
