/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jogamp_common_nio_PointerBuffer */

#ifndef _Included_com_jogamp_common_nio_PointerBuffer
#define _Included_com_jogamp_common_nio_PointerBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jogamp_common_nio_PointerBuffer
 * Method:    getDirectBufferAddressImpl
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_com_jogamp_common_nio_PointerBuffer_getDirectBufferAddressImpl
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
