/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jogamp_common_util_JarUtil */

#ifndef _Included_com_jogamp_common_util_JarUtil
#define _Included_com_jogamp_common_util_JarUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jogamp_common_util_JarUtil_BUFFER_SIZE
#define com_jogamp_common_util_JarUtil_BUFFER_SIZE 4096L
/*
 * Class:     com_jogamp_common_util_JarUtil
 * Method:    fixNativeLibAttribs
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_com_jogamp_common_util_JarUtil_fixNativeLibAttribs
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
