/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jogamp_common_os_MachineDataInfoRuntime */

#ifndef _Included_jogamp_common_os_MachineDataInfoRuntime
#define _Included_jogamp_common_os_MachineDataInfoRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getPointerSizeInBytesImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getPointerSizeInBytesImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getPageSizeInBytesImpl
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getPageSizeInBytesImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getAlignmentInt8Impl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getAlignmentInt8Impl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getAlignmentInt16Impl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getAlignmentInt16Impl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getAlignmentInt32Impl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getAlignmentInt32Impl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getAlignmentInt64Impl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getAlignmentInt64Impl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getAlignmentIntImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getAlignmentIntImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getAlignmentLongImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getAlignmentLongImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getAlignmentPointerImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getAlignmentPointerImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getAlignmentFloatImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getAlignmentFloatImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getAlignmentDoubleImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getAlignmentDoubleImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getAlignmentLongDoubleImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getAlignmentLongDoubleImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getSizeOfIntImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getSizeOfIntImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getSizeOfLongImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getSizeOfLongImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getSizeOfPointerImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getSizeOfPointerImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getSizeOfFloatImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getSizeOfFloatImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getSizeOfDoubleImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getSizeOfDoubleImpl
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_MachineDataInfoRuntime
 * Method:    getSizeOfLongDoubleImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_MachineDataInfoRuntime_getSizeOfLongDoubleImpl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
