/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jogamp_common_jvm_JVMUtil */

#ifndef _Included_jogamp_common_jvm_JVMUtil
#define _Included_jogamp_common_jvm_JVMUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jogamp_common_jvm_JVMUtil
 * Method:    initialize
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_jvm_JVMUtil_initialize
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
