/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jogamp_common_os_WindowsDynamicLinkerImpl */

#ifndef _Included_jogamp_common_os_WindowsDynamicLinkerImpl
#define _Included_jogamp_common_os_WindowsDynamicLinkerImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef jogamp_common_os_WindowsDynamicLinkerImpl_symbolArgAlignment
#define jogamp_common_os_WindowsDynamicLinkerImpl_symbolArgAlignment 4L
#undef jogamp_common_os_WindowsDynamicLinkerImpl_symbolMaxArguments
#define jogamp_common_os_WindowsDynamicLinkerImpl_symbolMaxArguments 12L
/*
 * Class:     jogamp_common_os_WindowsDynamicLinkerImpl
 * Method:    FreeLibrary
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_WindowsDynamicLinkerImpl_FreeLibrary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jogamp_common_os_WindowsDynamicLinkerImpl
 * Method:    GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_WindowsDynamicLinkerImpl_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_WindowsDynamicLinkerImpl
 * Method:    GetProcAddressA
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_WindowsDynamicLinkerImpl_GetProcAddressA
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jogamp_common_os_WindowsDynamicLinkerImpl
 * Method:    LoadLibraryW
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_WindowsDynamicLinkerImpl_LoadLibraryW
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
