/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jogamp_common_os_UnixDynamicLinkerImpl */

#ifndef _Included_jogamp_common_os_UnixDynamicLinkerImpl
#define _Included_jogamp_common_os_UnixDynamicLinkerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jogamp_common_os_UnixDynamicLinkerImpl
 * Method:    dlclose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_UnixDynamicLinkerImpl_dlclose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jogamp_common_os_UnixDynamicLinkerImpl
 * Method:    dlerror
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_UnixDynamicLinkerImpl_dlerror
  (JNIEnv *, jclass);

/*
 * Class:     jogamp_common_os_UnixDynamicLinkerImpl
 * Method:    dlopen
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_UnixDynamicLinkerImpl_dlopen
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     jogamp_common_os_UnixDynamicLinkerImpl
 * Method:    dlsym
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_de_dhbw_rahmlab_nativelibloader_impl_jogamp_common_os_UnixDynamicLinkerImpl_dlsym
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
